name: Terraform-Apply

on:
  pull_request:
    branches:
    #- env_*
    - master
    paths:
    - '*'
    - 'Test/*'
    - '!.github/*'
    #- '!*.md'
    types:
      - closed

jobs:
  Apply-to-AWS:
    runs-on: ubuntu-latest

    steps:     
      - name: pull
        uses: actions/checkout@master
        
      - name: terraform-init
        uses: canelkatmis/terraform-github-actions/init@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./Test
          TF_ACTION_TFE_TOKEN: ${{ secrets.TF_ACTION_TFE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: terraform-apply
        uses: canelkatmis/terraform-github-actions/apply@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./Test
          TF_ACTION_WORKSPACE : "default"
          TF_ACTION_TFE_TOKEN: ${{ secrets.TF_ACTION_TFE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: terraform-destroy
        uses: canelkatmis/terraform-github-actions/destroy@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./Test
          TF_ACTION_WORKSPACE : "default"
          TF_ACTION_TFE_TOKEN: ${{ secrets.TF_ACTION_TFE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
