name: Terraform-Apply

on:
  pull_request:
    branches:
    #- env_*
    - master
    paths:
    - '*'
    - 'Test/*'
    - '!.github/*'
    #- '!*.md'
    types:
      - closed

jobs:
  Apply-to-AWS:
    runs-on: ubuntu-latest

    steps:     
      - name: pull
        uses: actions/checkout@master
        
      - name: terraform-init
        uses: canelkatmis/terraform-github-actions@v0.5.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './Test'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_CLI_ARGS_init: '-backend-config="token=${{ secrets.TF_ACTION_TFE_TOKEN }}"'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: terraform-apply
        uses: canelkatmis/terraform-github-actions@v0.5.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: './Test'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: terraform-destroy
        uses: canelkatmis/terraform-github-actions@v0.5.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'destroy'
          tf_actions_working_dir: './Test'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
