name: Terraform-AWS

on: [pull_request]

jobs:
  Terraform-steps:

    runs-on: ubuntu-latest

    steps:
      - name: filter-to-pr-open-synced
        uses: actions/bin/filter@master

        with:
          args: action 'opened|synchronize'
 
  Terraform-steps2:

    runs-on: ubuntu-latest

      - name: terraform-fmt
        uses: hashicorp/terraform-github-actions/fmt@v0.3.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: "."
