name: Terraform-AWS

on: [pull_request]

jobs:
  filter-to-pr-open-synced:
    steps:
      - name: filter-to-pr-open-synced
        uses: actions/bin/filter@master

        with:
          args: action 'opened|synchronize'
      - run: echo filter Done!
      
  terraform-fmt:
    steps:
      - name: terraform-fmt
        uses: hashicorp/terraform-github-actions/fmt@v0.3.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: "."
      - run: echo fmt Done!
