name: Terraform-AWS

on:
  pull_request:
    branches:
    - master

jobs:

  Terraform-steps:

    runs-on: ubuntu-latest

    steps:

      - name: filter-to-pr-open-synced
        uses: actions/bin/filter@master
        with:
          args: action 'opened|synchronize'

      - name: pull
        uses: actions/checkout@master

      - name: terraform-format
        uses: hashicorp/terraform-github-actions/fmt@v0.3.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: "."

      - name: terraform-init
        uses: hashicorp/terraform-github-actions/init@v0.3.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: "."
          TF_ACTION_TFE_TOKEN: ${{ secrets.TF_ACTION_TFE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: terraform-validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: "."

      - name: terraform-plan
        uses: hashicorp/terraform-github-actions/plan@v0.3.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: "."
          TF_ACTION_WORKSPACE : "default"
          TF_ACTION_TFE_TOKEN: ${{ secrets.TF_ACTION_TFE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
