name: Terraform-Plan

on:
  pull_request:
    branches:
    - master
    #- env_*
    paths:
    - '*'
    - 'Test/*'
    - '!.github/*'
    #- '!*.md'
    
jobs:
  Plan-for-AWS:
    runs-on: ubuntu-latest
    env:
      TF_ACTION_VERSION: v0.5.0
    steps:
      - name: pull
        uses: actions/checkout@master

      - name: terraform-format
        uses: canelkatmis/terraform-github-actions/fmt@${{ TF_ACTION_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./Test

      - name: terraform-init
        uses: canelkatmis/terraform-github-actions/init@${{ TF_ACTION_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./Test
          TF_ACTION_TFE_TOKEN: ${{ secrets.TF_ACTION_TFE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: terraform-validate
        uses: canelkatmis/terraform-github-actions/validate@${{ TF_ACTION_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./Test

      - name: terraform-plan
        uses: canelkatmis/terraform-github-actions/plan@${{ TF_ACTION_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./Test
          TF_ACTION_WORKSPACE : "default"
          TF_ACTION_TFE_TOKEN: ${{ secrets.TF_ACTION_TFE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
